import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "@/style/global.scss";
import { ClerkProvider } from "@clerk/nextjs";
import { Suspense } from "react";
import Layout from "@/lib/layout/Layout";

const open_Sans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Cerebro",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  console.log("<layout>");

  return (
    <ClerkProvider>
      <html lang="en">
        <body className={open_Sans.className}>
          <Layout isMaxWidth>
            <Suspense>{children}</Suspense>
          </Layout>
        </body>
      </html>
    </ClerkProvider>
  );
}
